@startuml

package Domain {
    object Model
    object RepositoryInterface
}

package Repository {
    object DSL
    object RepositoryModel

    DSL --|> RepositoryInterface

    Repository <-> Database
}

package Database {
    object Migration
    object DatabaseModel

}

package UseCase {
    UseCase <-> Domain
    UseCase <-> Repository
}

package Controller {
    Controller <-> UseCase
}


package User {
    User <-> Controller
}

@enduml
