@startuml
'https://plantuml.com/class-diagram

entity "Article"  {
    id [PK]: UniqueId
    thumbnailPath: ImagePath
    title: ArticleTitle
    body: ArticleBody
    goodCount: GoodCount
}

entity "Comment" {
    id [PK]: UniqueId
    articleId: UniqueId
    name: CommentName
    body: CommentBody
}
Comment }-- Article

@enduml
