@startuml
'https://plantuml.com/class-diagram

entity "Article"  {
    id [PK]: UniqueId
    thumbnailPath: ImagePath
    title: ArticleTitle
    body: ArticleBody
    goodCount: GoodCount
}

entity "Comment" {
    id [PK]: UniqueId
    articleId: UniqueId
    body: CommentBody
}
Comment }-- Article

entity "CommentReply" {
    id [PK]: UniqueId
    commentId: UniqueId
    body: CommentBody
}
CommentReply }-- Comment

@enduml
